# Generated by Django 4.1.6 on 2023-02-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='produtos',
            field=models.ManyToManyField(to='clientes.produto'),
        ),
    ]
